jupiter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('production_scheduler.urls')),
    path('log/', include('log.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('login/',
        auth_views.LoginView.as_view(template_name='registration/login.html', redirect_authenticated_user=True),
        name='login'),
    path('logout/',
        auth_views.LogoutView.as_view(template_name='registration/logout.html'),
        name='logout'),
    path('password-reset/',
        auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),
        name='password_reset'),
    path('password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html'
        ),
        name='password_reset_confirm'),
    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'),
]

log/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required

from . import views

app_name = 'log'
urlpatterns = [
    path('view_log/<line_item_id>', views.view_log, name='view_log'),
    path('add_log_message/', views.add_log_message, name='add_log_message'),
]

production_scheduler/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required

from . import post_views
from . import new_orders_view
from . import historial_view

app_name = 'production_scheduler'
urlpatterns = [
    path('', new_orders_view.NewOrdersView.as_view(), name='new_orders'),
    path('historial/<option>/<filter>', historial_view.historial, name='historial'),
    path('assign_line_item_to_seamstress/<option>', post_views.assign_line_item_to_seamstress, name='assign_line_item_to_seamstress'),
    path('update_line_item_status/', post_views.update_line_item_status, name='update_line_item_status'),
    path('filter_line_items_by_seamstress/<callback>', post_views.filter_line_items_by_seamstress, name='filter_line_items_by_seamstress'),
]

log/models.py
from django.db import models
from django.conf import settings
from production_scheduler.models import LineItem

class Log(models.Model):
    line_item_id = models.ForeignKey(LineItem, on_delete=models.CASCADE)
    event_body = models.TextField()
    username = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    publication_date = models.DateTimeField(auto_now_add=True)
    is_event = models.BooleanField()

class InboxReadControl(models.Model):
    username = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    line_item_id = models.ForeignKey(LineItem, on_delete=models.CASCADE)
    last_event_viewed_date = models.DateTimeField()

production_scheduler/models.py
from django.db import models
from django.conf import settings

class Product(models.Model):
    product_sku = models.CharField(max_length=25, primary_key=True)
    product_name = models.CharField(max_length=200)
    nombre_producto = models.CharField(max_length=200)

    def __str__(self):
        return self.product_name


class Seamstress(models.Model):
    seamstress_id = models.AutoField(primary_key=True)
    alias = models.CharField(max_length=100, blank=True, null=True)
    username = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.alias

class LineItem(models.Model):
    line_item_id = models.CharField(max_length=50, primary_key=True)
    title = models.CharField(max_length=100)
    quantity = models.IntegerField()
    product_sku = models.CharField(max_length=25)
    variant_title = models.CharField(max_length=100)
    order_id = models.CharField(max_length=20)
    order_number = models.CharField(max_length=20)
    created_at = models.DateField()
    assigned_to = models.ForeignKey(Seamstress, on_delete=models.SET_NULL, blank=True, null=True)
    fecha_assignacion = models.DateField(blank=True, null=True)
    special_instructions = models.CharField(max_length=300, blank=True, null=True)
    #Choices
    NEW = 0
    ASSIGNED = 1
    CUTTING = 2
    ARMANDO = 3
    TERMINADA = 4
    ENTREGADA = 5
    ERROR = 6
    CORRIGIENDO = 7
    STATUS_CHOICES = (
    (NEW, 'Nueva'),
    (ASSIGNED, 'Asignada'),
    (CUTTING, 'Cortando'),
    (ARMANDO, 'Armando'),
    (TERMINADA, 'Terminada'),
    (ENTREGADA, 'Entregada'),
    (ERROR, 'Corregir Error'),
    (CORRIGIENDO, 'Corrigiendo')
    )
    status = models.IntegerField(default=0, choices=STATUS_CHOICES)
    fecha_entrega = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.title

log/forms.py
from django import forms
from django.shortcuts import render
from .models import Log

class LogForm(forms.ModelForm):
    event_body = forms.CharField(
                label=False,
                widget=forms.Textarea(
                        attrs={
                            'rows':4,
                            'cols':15,
                        }
                    )
                )
    class Meta:
        model = Log
        fields = [
            'event_body'
        ]

production_scheduler/forms.py
from django import forms
from django.shortcuts import render
from .models import Seamstress
from django.forms import ModelChoiceField

class SeamstressListForm(forms.Form):
    # #Choices#
    # TERMINADA = 4
    # ENTREGADA = 5
    # ERROR = 6
    # STATUS_CHOICES = (
    # (TERMINADA, 'Terminada'),
    # (ENTREGADA, 'Entregada'),
    # (ERROR, 'Corregir Error')
    # )
    # seamstress_id = forms.ChoiceField( label=False, choices=STATUS_CHOICES)
    seamstress_id = forms.ModelChoiceField(queryset=Seamstress.objects.all(), initial=0)
    #seamstress_id = forms.ChoiceField(label=False, choices=[(seamstress.seamstress_id, seamstress.alias) for seamstress in Seamstress.objects.all()])

class StatusForm(forms.Form):
    #Choices
    CUTTING = 2
    ARMANDO = 3
    TERMINADA = 4
    CORRIGIENDO = 7
    STATUS_CHOICES = (
    (CUTTING, 'Cortando'),
    (ARMANDO, 'Armando'),
    (TERMINADA, 'Terminada'),
    (CORRIGIENDO, 'Corrigiendo')
    )
    status = forms.ChoiceField( label=False, choices=STATUS_CHOICES)

class LineItemEntregadaForm(forms.Form):
    #Choices
    TERMINADA = 4
    ENTREGADA = 5
    ERROR = 6
    STATUS_CHOICES = (
    (TERMINADA, 'Terminada'),
    (ENTREGADA, 'Entregada'),
    (ERROR, 'Corregir Error')
    )
    status = forms.ChoiceField( label=False, choices=STATUS_CHOICES)

class LineItemSpecialInstructionsForm(forms.Form):
    nota = forms.CharField(
                label=False,required=False,
                widget=forms.Textarea(
                        attrs={
                            'rows':4,
                            'cols':15,
                            #'class': 'my-class',
                            #'id': 'my-id'
                        }
                    )
                )

log/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import Http404
from django.contrib.auth.decorators import login_required
from production_scheduler.models import LineItem
from .models import Log
from .db_manipulation import *
from .forms import *
from users.models import CustomUser

@login_required()
def view_log(request, line_item_id):
    template_name = 'log/log.html'
    form = LogForm
    user_id = request.user.id
    log = retrieve_line_item_log__(line_item_id, user_id)
    context = {
                'line_item_id':line_item_id,
                'form':form,
                'log':log
            }
    return render(request, template_name, context)

@login_required()
def add_log_message(request):
    if (request.method == "POST"):
        event_body = request.POST['event_body']
        line_item_id = request.POST['line_item_id']
        log = Log(
                    line_item_id= LineItem.objects.get(pk=line_item_id),
                    event_body = event_body,
                    username=CustomUser.objects.get(pk=request.user.id),
                    is_event = False
                )
        log.save()
        return redirect('log:view_log', line_item_id=line_item_id)
    raise(Http404)

production_scheduler/templates/production_scheduler/historial.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% load user_group_validation %}
{% load zip %}

{% block content %}
{% if coordinator == True %}
  <h2>{{ option }}</h2>
    <div class="row">
      <div class="col-sm-3">
        <form method="POST" id="filter_line_items_by_seamstress" action="{% url 'production_scheduler:filter_line_items_by_seamstress' callback=option %}">
          {% csrf_token %}
          {{ seamstressListForm| crispy}}
          <button type="submit" name='action' value = 'filter' class="btn btn-sm btn-dark">Filtrar</button>
          <button type="submit" name='action' value = 'reset' class="btn btn-sm btn-dark">Reset</button>
        </form>
      </div>
  </div>
{% endif %}
<br>
<div class="table-responsive">
<table id ="new_orders_table" class="table table-hover" cellspacing="0">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col" onclick="sortTable(1, 'new_orders_table')"># Orden <i class="fa fa-fw fa-sort"></th>
      <th scope="col">Producto</th>
      <th scope="col">Cantidad</th>
      <th scope="col">Fecha Orden</th>
      <th scope="col">Fecha Asignación</th>
      <th scope="col">Asignado a</th>
      <th scope="col">Estado</th>
      <th scope="col">Entregado</th>
      <th scope="col">Nota</th>
      <th scope="col">Detalles</th>
      <th scope="col">Log</th>
      {% if entregadas == True  or terminadas == True %}
        <th scope="col">Cambiar Estado</th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for line_item, new_activity in line_items_list|zip:new_activity_ls %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ line_item.order_number }}</td>
        <td>{{ line_item.title }}</td>
        <td>{{ line_item.quantity }}</td>
        <td>{{ line_item.created_at }}</td>
        <td>{{ line_item.fecha_assignacion }}</td>
        <td>{{ line_item.assigned_to }}</td>
        <td>{{ line_item.get_status_display }}</td>
        <td>{{ line_item.fecha_entrega }}</td>
        <td>
          <button type="button" class="btn btn-sm btn-dark" title="Nota" data-toggle="popover"  data-trigger="hover" data-placement="left" data-content= '{{ line_item.special_instructions }}'>
            <svg class="bi bi-eye-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path d="M10.5 8a2.5 2.5 0 11-5 0 2.5 2.5 0 015 0z"/>
              <path fill-rule="evenodd" d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 100-7 3.5 3.5 0 000 7z" clip-rule="evenodd"/>
            </svg>
          </button>
        </td>
        <td>
          <button type="button" class="btn btn-sm btn-dark" title="Detalles" data-toggle="popover" data-trigger="hover" data-content= '{{ line_item.variant_title }}'>
            <svg class="bi bi-eye-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path d="M10.5 8a2.5 2.5 0 11-5 0 2.5 2.5 0 015 0z"/>
              <path fill-rule="evenodd" d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 100-7 3.5 3.5 0 000 7z" clip-rule="evenodd"/>
            </svg>
          </button>
        </td>
        <td>
          <a href="{% url 'log:view_log' line_item.line_item_id %}" class="text-dark">
            <svg class="bi bi-archive" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M2 5v7.5c0 .864.642 1.5 1.357 1.5h9.286c.715 0 1.357-.636 1.357-1.5V5h1v7.5c0 1.345-1.021 2.5-2.357 2.5H3.357C2.021 15 1 13.845 1 12.5V5h1z" clip-rule="evenodd"/>
              <path fill-rule="evenodd" d="M5.5 7.5A.5.5 0 016 7h4a.5.5 0 010 1H6a.5.5 0 01-.5-.5zM15 2H1v2h14V2zM1 1a1 1 0 00-1 1v2a1 1 0 001 1h14a1 1 0 001-1V2a1 1 0 00-1-1H1z" clip-rule="evenodd"/>
            </svg>
            {% if new_activity == True %}
            <svg class="bi bi-exclamation-circle" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M8 15A7 7 0 108 1a7 7 0 000 14zm0 1A8 8 0 108 0a8 8 0 000 16z" clip-rule="evenodd"/>
              <path d="M7.002 11a1 1 0 112 0 1 1 0 01-2 0zM7.1 4.995a.905.905 0 111.8 0l-.35 3.507a.552.552 0 01-1.1 0L7.1 4.995z"/>
            </svg>
            {% endif %}
          </a>
        </td>
        {% if entregadas == True  or terminadas == True %}
          <td>
            <form method="POST" action="{% url 'production_scheduler:update_line_item_status' %}">
              {% csrf_token %}
              {{ lineItemEntregadaForm | crispy }}
              <input type="hidden" id="line_item_id" name="line_item_id" value='{{ line_item.line_item_id }}'>
              <input type="hidden" id="update_line_item_status" name="update_line_item_status">
              <input type="hidden" id="option" name="option" value='{{ option }}'>
              <button type="submit" class="btn btn-sm btn-dark">Actualizar</button>
            </form>
          </td>
        {% endif %}
      </tr>
    {% endfor %}
  </tbody>
</table>
</div>

{% endblock content %}

production_scheduler/templates/production_scheduler/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% load user_group_validation %}

{% block content %}

{% if http_status != 200 %}
  <h4>HTTP Error {{ http_status }}. Couldn't retrieve new orders </h4>
{% endif %}
{% if timeout == True %}
  <h4>Error: Conection timeout. Couldn't retrieve new orders.</h4>
{% endif %}
{% if connection_error == True %}
  <h4>Error: Connection Error. Couldn't retrieve new orders. </h4>
{% endif %}

<br>
<div class="table-responsive">
<table id ="new_orders_table" class="table table-striped table-bordered .table-hover" cellspacing="0">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col" onclick="sortTable(1, 'new_orders_table')"># Orden <i class="fa fa-fw fa-sort"></th>
      <th scope="col">Producto</th>
      <th scope="col">Cantidad</th>
      <th scope="col">Fecha Orden</th>
      <th scope="col">Asignado a</th>
      <th scope="col">Estado</th>
      <th scope="col">Entregado</th>
      <th scope="col">Nota</th>
      <th scope="col">Detalles</th>
      {% if request.user|has_group:"coordinator" %}
        <th scope="col">Asignar</th>
      {% endif %}
      {% if request.user|has_group:"coordinator" %}
        <th scope="col">Marcar cómo asignada</th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for line_item in line_items_list %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ line_item.order_number }}</td>
        <td>{{ line_item.title }}</td>
        <td>{{ line_item.quantity }}</td>
        <td>{{ line_item.created_at }}</td>
        <td id='{{ line_item.line_item_id }}assigned_field'>{{ line_item.assigned_to }}</td>
        <td>{{ line_item.get_status_display }}</td>
        <td>{{ line_item.fecha_entrega }}</td>
        <td>{{ line_item.special_instructions }}</td>
        <td>
          <button type="button" class="btn btn-sm btn-dark" title="Detalles" data-toggle="popover" data-content= '{{ line_item.variant_title }}' >Ver</button>
        </td>
        {% if request.user|has_group:"coordinator" %}
        <td>
          <form method="POST" class="assignment_form" action="{% url 'production_scheduler:assign_line_item_to_seamstress' %}">
            {% csrf_token %}
            {{ form| crispy}}
            <input type="hidden" id="line_item_id" name="line_item_id" value='{{ line_item.line_item_id }}'>
            <input type="hidden" id="assign_line_item_to_seamstress" name="assign_line_item_to_seamstress">
            <button type="submit" class="btn btn-sm btn-block btn-dark">Asignar</button>
          </form>
        </td>
        {% endif %}
        {% if request.user|has_group:"coordinator" %}
        <td>
          <form method="POST" class="dismiss" action="{% url 'production_scheduler:change_line_item_status' %}">
            {% csrf_token %}
            <input type="hidden" id="line_item_id" name="line_item_id" value='{{ line_item.line_item_id }}'>
            <input type="hidden" id="change_line_item_status" name="change_line_item_status">
            <button type="submit" class="btn btn-sm btn-dark">Dismiss</button>
          </form>
        </td>
        {% endif %}
      </tr>
    {% endfor %}
  </tbody>
</table>
</div>

{% endblock content %}

production_scheduler/templates/production_scheduler/log.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% load user_group_validation %}

{% block content %}
<div class="my-3 p-3 bg-white rounded box-shadow">
  <h6 class="border-bottom border-gray pb-2 mb-0">Log Orden # {{ line_item_id }}</h6>
  {% for event in log %}
    <div class="media text-muted pt-3">
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">
          {% if event.is_event == False %}
            @{{ event.username }}
          {% else %}
            System event
          {% endif %}
          on {{ event.publication_date }}
        </strong> {{ event.event_body }}
    </div>
  {% endfor %}
</div>

<form method="POST" action="{% url 'production_scheduler:add_log_message' %}">
  {% csrf_token %}
  {{ form| crispy}}
  <input type="hidden" id="line_item_id" name="line_item_id" value='{{ line_item_id }}'>
  <button type="submit" class="btn btn-sm btn-block btn-dark">Enviar</button>
</form>
{% endblock content %}

production_scheduler/templates/production_scheduler/mis-ordenes.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% load user_group_validation %}
{% load zip %}

{% block content %}
<br>
<div class="table-responsive">
<table id ="new_orders_table" class="table table-hover" cellspacing="0">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col"># Orden <i class="fa fa-fw fa-sort"></th>
      <th scope="col">Producto</th>
      <th scope="col">Cantidad</th>
      <th scope="col">Fecha Orden</th>
      <th scope="col">Fecha Asignación</th>
      <th scope="col">Asignado a</th>
      <th scope="col">Estado</th>
      <th scope="col">Entregado</th>
      <th scope="col">Nota</th>
      <th scope="col">Detalles</th>
      <th scrope="col">Log</th>
      <th scope="col">Actualizar Estado</th>
    </tr>
  </thead>
  <tbody>
    {% for line_item, new_activity in line_items_list|zip:new_activity_ls %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ line_item.order_number }}</td>
        <td>{{ line_item.title }}</td>
        <td>{{ line_item.quantity }}</td>
        <td>{{ line_item.created_at }}</td>
        <td>{{ line_item.fecha_assignacion }}</td>
        <td>{{ line_item.assigned_to }}</td>
        <td id='{{ line_item.line_item_id }}status_field'>{{ line_item.get_status_display }}</td>
        <td>{{ line_item.fecha_entrega }}</td>
        <td>
          <button type="button" class="btn btn-sm btn-dark" title="Nota" data-toggle="popover"  data-trigger="hover" data-placement="left" data-content= '{{ line_item.special_instructions }}'>
            <svg class="bi bi-eye-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path d="M10.5 8a2.5 2.5 0 11-5 0 2.5 2.5 0 015 0z"/>
              <path fill-rule="evenodd" d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 100-7 3.5 3.5 0 000 7z" clip-rule="evenodd"/>
            </svg>
          </button>
        </td>
        <td>
          <button type="button" class="btn btn-sm btn-dark" title="Detalles" data-trigger="hover" data-toggle="popover" data-content= '{{ line_item.variant_title }}'>
            <svg class="bi bi-eye-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path d="M10.5 8a2.5 2.5 0 11-5 0 2.5 2.5 0 015 0z"/>
              <path fill-rule="evenodd" d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 100-7 3.5 3.5 0 000 7z" clip-rule="evenodd"/>
            </svg>
          </button>
        </td>
        <td>
          <a href="{% url 'log:view_log' line_item.line_item_id %}" class="text-dark">
            <svg class="bi bi-archive" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M2 5v7.5c0 .864.642 1.5 1.357 1.5h9.286c.715 0 1.357-.636 1.357-1.5V5h1v7.5c0 1.345-1.021 2.5-2.357 2.5H3.357C2.021 15 1 13.845 1 12.5V5h1z" clip-rule="evenodd"/>
              <path fill-rule="evenodd" d="M5.5 7.5A.5.5 0 016 7h4a.5.5 0 010 1H6a.5.5 0 01-.5-.5zM15 2H1v2h14V2zM1 1a1 1 0 00-1 1v2a1 1 0 001 1h14a1 1 0 001-1V2a1 1 0 00-1-1H1z" clip-rule="evenodd"/>
            </svg>
            {% if new_activity == True %}
            <svg class="bi bi-exclamation-circle" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M8 15A7 7 0 108 1a7 7 0 000 14zm0 1A8 8 0 108 0a8 8 0 000 16z" clip-rule="evenodd"/>
              <path d="M7.002 11a1 1 0 112 0 1 1 0 01-2 0zM7.1 4.995a.905.905 0 111.8 0l-.35 3.507a.552.552 0 01-1.1 0L7.1 4.995z"/>
            </svg>
            {% endif %}
          </a>
        </td>
        <td>
          <form method="POST" class="update_line_item_status" action="{% url 'production_scheduler:update_line_item_status' %}">
            {% csrf_token %}
            {{ form| crispy}}
            <input type="hidden" id="line_item_id" name="line_item_id" value='{{ line_item.line_item_id }}'>
            <input type="hidden" id="update_line_item_status" name="update_line_item_status">
            <button type="submit" class="btn btn-sm btn-block btn-dark">Actualizar</button>
          </form>
        </td>
      </tr>
      {% empty %}
        <tr><h4>No hay nuevas ordenes.</h4></tr><br>
    {% endfor %}
  </tbody>
</table>
</div>

{% endblock content %}

production_scheduler/templates/production_scheduler/new_orders.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% load user_group_validation %}

{% block content %}

<br>
<div class="table-responsive">
<table id ="new_orders_table" class="table table-hover" cellspacing="0">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col" onclick="sortTable(1, 'new_orders_table')"># Orden <i class="fa fa-fw fa-sort"></th>
      <th scope="col">Producto</th>
      <th scope="col">Cantidad</th>
      <th scope="col">Fecha Orden</th>
      <th scope="col">Fecha Asignacion</th>
      <th scope="col">Asignado a</th>
      <th scope="col">Estado</th>
      <th scope="col">Entregado</th>
      <th scope="col">Detalles</th>
      <th scope="col">Marcar cómo asignada</th>
      {% if request.user|has_group:"coordinator" %}
        <th scope="col">Agregar Nota/Dismiss</th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
    {% for line_item in line_items_list %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ line_item.order_number }}</td>
        <td>{{ line_item.title }}</td>
        <td>{{ line_item.quantity }}</td>
        <td>{{ line_item.created_at }}</td>
        <td>{{ line_item.fecha_assignacion }}</td>
        <td id='{{ line_item.line_item_id }}assigned_field'>{{ line_item.assigned_to }}</td>
        <td>{{ line_item.get_status_display }}</td>
        <td>{{ line_item.fecha_entrega }}</td>
        <td>
          <button type="button" class="btn btn-sm btn-dark" title="Detalles" data-trigger="hover" data-toggle="popover" data-content= '{{ line_item.variant_title }}'>
            <svg class="bi bi-eye-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path d="M10.5 8a2.5 2.5 0 11-5 0 2.5 2.5 0 015 0z"/>
              <path fill-rule="evenodd" d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8zm8 3.5a3.5 3.5 0 100-7 3.5 3.5 0 000 7z" clip-rule="evenodd"/>
            </svg>
          </button>
        </td>
        {% if request.user|has_group:"coordinator" %}
        <td>
          <form method="POST" class="assignment_form" action="{% url 'production_scheduler:assign_line_item_to_seamstress' option='assign' %}">
            {% csrf_token %}
            {{ form| crispy}}
            <input type="hidden" id="line_item_id" name="line_item_id" value='{{ line_item.line_item_id }}'>
            <input type="hidden" id="assign_line_item_to_seamstress" name="assign_line_item_to_seamstress">
            <button type="submit" class="btn btn-sm btn-block btn-dark">Asignar</button>
          </form>
        </td>
        {% endif %}
        {% if request.user|has_group:"coordinator" %}
        <td>
          <form method="POST" class="dismiss" action="{% url 'production_scheduler:assign_line_item_to_seamstress' option='change_status' %}">
            {% csrf_token %}
            {{ lineItemSpecialInstructionsForm | crispy }}
            <input type="hidden" id="line_item_id" name="line_item_id" value='{{ line_item.line_item_id }}'>
            <input type="hidden" id="uptdate_line_item_status_to_assigned" name="uptdate_line_item_status_to_assigned">
            <button type="submit" class="btn btn-sm btn-block btn-dark">Confirmar Asignación</button>
          </form>
        </td>
        {% endif %}
      </tr>
      {% empty %}
        <tr><h4>No hay nuevos ordenes.</h4></tr><br>
    {% endfor %}
  </tbody>
</table>
</div>

{% endblock content %}