jupiter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('production_scheduler.urls')),
    path('log/', include('log.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('login/',
        auth_views.LoginView.as_view(template_name='registration/login.html', redirect_authenticated_user=True),
        name='login'),
    path('logout/',
        auth_views.LogoutView.as_view(template_name='registration/logout.html'),
        name='logout'),
    path('password-reset/',
        auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),
        name='password_reset'),
    path('password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html'
        ),
        name='password_reset_confirm'),
    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'),
]

log/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required

from . import views

app_name = 'log'
urlpatterns = [
    path('view_log/<line_item_id>', views.view_log, name='view_log'),
    path('add_log_message/', views.add_log_message, name='add_log_message'),
]

production_scheduler/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required

from . import post_views
from . import new_orders_view
from . import historial_view

app_name = 'production_scheduler'
urlpatterns = [
    path('', new_orders_view.NewOrdersView.as_view(), name='new_orders'),
    path('historial/<option>/<filter>', historial_view.historial, name='historial'),
    path('assign_line_item_to_seamstress/<option>', post_views.assign_line_item_to_seamstress, name='assign_line_item_to_seamstress'),
    path('update_line_item_status/', post_views.update_line_item_status, name='update_line_item_status'),
    path('filter_line_items_by_seamstress/<callback>', post_views.filter_line_items_by_seamstress, name='filter_line_items_by_seamstress'),
]

production_scheduler/models.py
from django.db import models
from django.conf import settings

class Product(models.Model):
    product_sku = models.CharField(max_length=25, primary_key=True)
    product_name = models.CharField(max_length=200)
    nombre_producto = models.CharField(max_length=200)

    def __str__(self):
        return self.product_name


class Seamstress(models.Model):
    seamstress_id = models.AutoField(primary_key=True)
    alias = models.CharField(max_length=100, blank=True, null=True)
    username = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.alias

class LineItem(models.Model):
    line_item_id = models.CharField(max_length=50, primary_key=True)
    title = models.CharField(max_length=100)
    quantity = models.IntegerField()
    product_sku = models.CharField(max_length=25)
    variant_title = models.CharField(max_length=100)
    order_id = models.CharField(max_length=20)
    order_number = models.CharField(max_length=20)
    created_at = models.DateField()
    assigned_to = models.ForeignKey(Seamstress, on_delete=models.SET_NULL, blank=True, null=True)
    fecha_assignacion = models.DateField(blank=True, null=True)
    special_instructions = models.CharField(max_length=300, blank=True, null=True)
    #Choices
    NEW = 0
    ASSIGNED = 1
    CUTTING = 2
    ARMANDO = 3
    TERMINADA = 4
    ENTREGADA = 5
    ERROR = 6
    CORRIGIENDO = 7
    STATUS_CHOICES = (
    (NEW, 'Nueva'),
    (ASSIGNED, 'Asignada'),
    (CUTTING, 'Cortando'),
    (ARMANDO, 'Armando'),
    (TERMINADA, 'Terminada'),
    (ENTREGADA, 'Entregada'),
    (ERROR, 'Corregir Error'),
    (CORRIGIENDO, 'Corrigiendo')
    )
    status = models.IntegerField(default=0, choices=STATUS_CHOICES)
    fecha_entrega = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.title

production_scheduler/forms.py
from django import forms
from django.shortcuts import render
from .models import Seamstress
from django.forms import ModelChoiceField

class SeamstressListForm(forms.Form):
    # #Choices#
    # TERMINADA = 4
    # ENTREGADA = 5
    # ERROR = 6
    # STATUS_CHOICES = (
    # (TERMINADA, 'Terminada'),
    # (ENTREGADA, 'Entregada'),
    # (ERROR, 'Corregir Error')
    # )
    # seamstress_id = forms.ChoiceField( label=False, choices=STATUS_CHOICES)
    seamstress_id = forms.ModelChoiceField(queryset=Seamstress.objects.all(), initial=0)
    #seamstress_id = forms.ChoiceField(label=False, choices=[(seamstress.seamstress_id, seamstress.alias) for seamstress in Seamstress.objects.all()])

class StatusForm(forms.Form):
    #Choices
    CUTTING = 2
    ARMANDO = 3
    TERMINADA = 4
    CORRIGIENDO = 7
    STATUS_CHOICES = (
    (CUTTING, 'Cortando'),
    (ARMANDO, 'Armando'),
    (TERMINADA, 'Terminada'),
    (CORRIGIENDO, 'Corrigiendo')
    )
    status = forms.ChoiceField( label=False, choices=STATUS_CHOICES)

class LineItemEntregadaForm(forms.Form):
    #Choices
    TERMINADA = 4
    ENTREGADA = 5
    ERROR = 6
    STATUS_CHOICES = (
    (TERMINADA, 'Terminada'),
    (ENTREGADA, 'Entregada'),
    (ERROR, 'Corregir Error')
    )
    status = forms.ChoiceField( label=False, choices=STATUS_CHOICES)

class LineItemSpecialInstructionsForm(forms.Form):
    nota = forms.CharField(
                label=False,required=False,
                widget=forms.Textarea(
                        attrs={
                            'rows':4,
                            'cols':15,
                            #'class': 'my-class',
                            #'id': 'my-id'
                        }
                    )
                )

production_scheduler/templates/base.html
{% load static %}
{% load user_group_validation %}

<!DOCTYPE html>
<html lang="es" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!--Login CSS-->
    <link href="{% static 'production_scheduler/css/login.css' %}" rel="stylesheet">

    <title>Production Scheduler</title>


    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- Production Scheduler JavaScript-->
    <script src="{% static 'production_scheduler/js/production_scheduler.js' %}"></script>

  </head>
  <body>
      <!--Navegation Bar-->
      <nav class="navbar navbar-dark bg-dark navbar-expand-md fixed-top">
        <a class="navbar-brand" href="#">Remu Apparel</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'production_scheduler:new_orders' %}">Nuevas Ordenes <span class="sr-only">(current)</span></a>
            </li>
            {% if request.user|has_group:"coordinator" %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Ordenes Asignadas
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'production_scheduler:historial' option='produccion' filter='none' %}">En Producción</a>
                  <a class="dropdown-item" href="{% url 'production_scheduler:historial' option='terminadas' filter='none' %}">Terminadas</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{% url 'production_scheduler:historial' option='entregadas' filter='none' %}">Entregadas</a>
                </div>
              </li>
            {% endif %}
            {% if request.user|has_group:"seamstress" %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'production_scheduler:historial' option='costurera' filter='none' %}">Historial</a>
              </li>
            {% endif %}

          </ul>
          <ul class="nav navbar-nav navbar-right">
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <p class="nav-item nav-link disabled">Hola, {{ user.username }}</p>
                <a class="nav-item nav-link" href="#">Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">
                  <svg class="bi bi-box-arrow-in-right" width="2em" height="2em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M8.146 11.354a.5.5 0 010-.708L10.793 8 8.146 5.354a.5.5 0 11.708-.708l3 3a.5.5 0 010 .708l-3 3a.5.5 0 01-.708 0z" clip-rule="evenodd"/>
                    <path fill-rule="evenodd" d="M1 8a.5.5 0 01.5-.5h9a.5.5 0 010 1h-9A.5.5 0 011 8z" clip-rule="evenodd"/>
                    <path fill-rule="evenodd" d="M13.5 14.5A1.5 1.5 0 0015 13V3a1.5 1.5 0 00-1.5-1.5h-8A1.5 1.5 0 004 3v1.5a.5.5 0 001 0V3a.5.5 0 01.5-.5h8a.5.5 0 01.5.5v10a.5.5 0 01-.5.5h-8A.5.5 0 015 13v-1.5a.5.5 0 00-1 0V13a1.5 1.5 0 001.5 1.5h8z" clip-rule="evenodd"/>
                  </svg>
                </a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
              {% endif %}
            </div>
          </ul>
        </div>
      </nav>

    <main role="main" class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              {{ message }}
            </div>
          {% endfor %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>


    <script type="text/javascript">
      $(document).ready(function(){
        //Data Popover
        $('[data-toggle="popover"]').popover();
      });

      $(document).ready(function(){
        //Ajax Call LineItem Seamstress Assigment Form
        $('.assignment_form').submit(function(event){
          event.preventDefault();
          var $formData = $(this).serialize()
          var $thisURL = $('.assignment_form').attr('action') //|| window.location.href
          $.ajax({
            method: "POST",
            url: $thisURL,
            data: $formData,
            success: handleFormSuccess,
            error: handleFormError,
          })
          function handleFormSuccess(data, textStatus, jqXHR){
            console.log(data)
            console.log(textStatus)
            console.log(jqXHR)
            var $line_item_id = data.line_item_id
            var $assign_field = $line_item_id + 'assigned_field'
            $('#' + $assign_field).html(data.assigned_to);
          }

          function handleFormError(jqXHR, textStatus, errorThrown){
              console.log(jqXHR)
              console.log(textStatus)
              console.log(errorThrown)
          }

        });

        //Ajax Call LineItem StatusForm
        $('.update_line_item_status').submit(function(event){
          event.preventDefault();
          var $formData = $(this).serialize()
          var $thisURL = $('.update_line_item_status').attr('action')
          $.ajax({
            method: "POST",
            url: $thisURL,
            data: $formData,
            success: handleFormSuccess,
            error: handleFormError,
          })
          function handleFormSuccess(data, textStatus, jqXHR){
            console.log(data)
            console.log(textStatus)
            console.log(jqXHR)
            var $line_item_id = data.line_item_id
            var $status_field = $line_item_id + 'status_field'
            $('#' + $status_field).html(data.new_status);
          }

          function handleFormError(jqXHR, textStatus, errorThrown){
              console.log(jqXHR)
              console.log(textStatus)
              console.log(errorThrown)
          }

        });
      });
      //End document.ready
    </script>
</body>
</html>