jupiter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('production_scheduler.urls')),
    path('log/', include('log.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('login/',
        auth_views.LoginView.as_view(template_name='registration/login.html', redirect_authenticated_user=True),
        name='login'),
    path('logout/',
        auth_views.LogoutView.as_view(template_name='registration/logout.html'),
        name='logout'),
    path('password-reset/',
        auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),
        name='password_reset'),
    path('password-reset/done/',
        auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html'
        ),
        name='password_reset_confirm'),
    path('password-reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'),
]

log/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required, permission_required

from . import views

app_name = 'log'
urlpatterns = [
    path('view_log/<line_item_id>', views.view_log, name='view_log'),
    path('add_log_message/', views.add_log_message, name='add_log_message'),
]

log/models.py
from django.db import models
from django.conf import settings
from production_scheduler.models import LineItem

class Log(models.Model):
    line_item_id = models.ForeignKey(LineItem, on_delete=models.CASCADE)
    event_body = models.TextField()
    username = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    publication_date = models.DateTimeField(auto_now_add=True)
    is_event = models.BooleanField()

class InboxReadControl(models.Model):
    username = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    line_item_id = models.ForeignKey(LineItem, on_delete=models.CASCADE)
    last_event_viewed_date = models.DateTimeField()

log/forms.py
from django import forms
from django.shortcuts import render
from .models import Log

class LogForm(forms.ModelForm):
    event_body = forms.CharField(
                label=False,
                widget=forms.Textarea(
                        attrs={
                            'rows':4,
                            'cols':15,
                        }
                    )
                )
    class Meta:
        model = Log
        fields = [
            'event_body'
        ]

log/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import Http404
from django.contrib.auth.decorators import login_required
from production_scheduler.models import LineItem
from .models import Log
from .db_manipulation import *
from .forms import *
from users.models import CustomUser

@login_required()
def view_log(request, line_item_id):
    template_name = 'log/log.html'
    form = LogForm
    user_id = request.user.id
    log = retrieve_line_item_log__(line_item_id, user_id)
    context = {
                'line_item_id':line_item_id,
                'form':form,
                'log':log
            }
    return render(request, template_name, context)

@login_required()
def add_log_message(request):
    if (request.method == "POST"):
        event_body = request.POST['event_body']
        line_item_id = request.POST['line_item_id']
        log = Log(
                    line_item_id= LineItem.objects.get(pk=line_item_id),
                    event_body = event_body,
                    username=CustomUser.objects.get(pk=request.user.id),
                    is_event = False
                )
        log.save()
        return redirect('log:view_log', line_item_id=line_item_id)
    raise(Http404)

log/templates/log/log.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% load user_group_validation %}

{% block content %}
<div class="my-3 p-3 bg-white rounded box-shadow">
  <h6 class="border-bottom border-gray pb-2 mb-0">Log Orden # {{ line_item_id }}</h6>
  {% for event in log %}
    <div class="media text-muted pt-3">
      <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">
          {% if event.is_event == False %}
            @{{ event.username }}
          {% else %}
            System event
          {% endif %}
          on {{ event.publication_date }}
        </strong> {{ event.event_body }}
    </div>
  {% endfor %}
</div>

<form method="POST" action="{% url 'log:add_log_message' %}">
  {% csrf_token %}
  {{ form| crispy}}
  <input type="hidden" id="line_item_id" name="line_item_id" value='{{ line_item_id }}'>
  <button type="submit" class="btn btn-sm btn-block btn-dark">Enviar</button>
</form>
{% endblock content %}